#!/bin/bash -e

mvn package -DskipTests

(cd scripts/docker/experiment && docker-compose stop && docker-compose rm -f)

rm -rf scripts/docker/experiment/runtime/*.jar
rm -rf scripts/docker/experiment/dataset/*.json

cp experiment/sample-stream/target/sample-stream-jar-with-dependencies.jar   scripts/docker/experiment/runtime/

(cd scripts/docker/experiment && docker-compose up -d)